# Generated by Django 3.1.5 on 2021-01-08 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('temp', models.CharField(max_length=50)),
                ('feels_like', models.CharField(max_length=50)),
                ('temp_min', models.CharField(max_length=50)),
                ('pressure', models.CharField(max_length=50)),
                ('humidity', models.CharField(max_length=50)),
                ('visibility', models.CharField(max_length=50)),
                ('iconUrl', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.user')),
            ],
        ),
    ]
