# Generated by Django 3.1.5 on 2021-01-09 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0002_weatherdataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=50)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.user')),
            ],
        ),
        migrations.AlterField(
            model_name='weatherdataset',
            name='dataset_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.datasets'),
        ),
    ]
